name: Pages

on:
    push:
        branches:
            - main # default branch

jobs:
    pages:
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
            - name: Check out branch
              uses: actions/checkout@v3

            - name: Use Latest Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "latest"

            - name: Install Pnpm
              uses: pnpm/action-setup@v2
              with:
                  version: "latest"
                  run_install: false

            - name: Get pnpm store directory
              id: pnpm-cache
              shell: bash
              run: |
                  echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

            - uses: actions/cache@v3
              name: Setup pnpm cache
              with:
                  path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
                  key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
                  restore-keys: |
                      ${{ runner.os }}-pnpm-store-

            - name: Pull Theme
              run: git submodule update --init

            - name: Install Dependencies
              run: pnpm install

            - name: Generate Pages
              run: pnpm g

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./public
                  cname: blog.nvimer.org
